import React,{useState}from'react';import{ChevronDown}from'lucide-react';import BackArrow from'./BackArrow';
const FAQS=[
['Comment passer une commande ?','Parcourez la carte, ajoutez vos plats au panier, puis finalisez votre commande en choisissant le mode de réception (sur place, livraison ou à emporter) et le moyen de paiement.'],
['Quels sont les délais de livraison ?','La livraison à Libreville prend généralement 25 à 35 minutes. Pour les commandes sur place ou à emporter, comptez 15 à 20 minutes de préparation.'],
['Comment suivre ma commande ?','Après confirmation, vous recevez un numéro de commande et un QR code scannable. Suivez l\'état (confirmée, préparation, en route, livrée) dans la section « Mes commandes » ou via le QR code.'],
['Puis-je modifier ou annuler ma commande ?','Vous pouvez annuler tant que le statut est « confirmée ». Contactez-nous rapidement au numéro affiché dans l\'application.'],
['Quels moyens de paiement acceptez-vous ?','Mobile Money (Airtel Money, Moov Money) ou paiement sur place.'],
['Comment réserver une table ?','Rendez-vous dans la section « Réserver », choisissez la date, l\'heure et le nombre de convives, puis confirmez.'],
['Mon QR code ne fonctionne pas, que faire ?','Chaque QR code est unique et lié à votre numéro de commande. Assurez-vous de scanner le bon code. Si le problème persiste, contactez-nous.'],
['Proposez-vous des options végétariennes ?','Oui, plusieurs plats végétariens sont disponibles. Filtrez la carte ou demandez conseil à notre équipe.']
];
export default function FAQScreen(){const[open,setOpen]=useState(null);return <main className="screen"><div className="title-row"><BackArrow to="home" force/><h1>Aide & FAQ</h1><span/></div><small>QUESTIONS FRÉQUENTES</small><h1 style={{fontFamily:'Georgia,serif',fontSize:32,margin:'8px 0 20px'}}>On vous aide</h1><div className="profile-links">{FAQS.map(([q,a],i)=>{const isOpen=open===i;return <div key={i} style={{background:'var(--caprice-card)',borderRadius:16,overflow:'hidden',margin:'8px 0'}}><button onClick={()=>setOpen(isOpen?null:i)} style={{width:'100%',display:'flex',justifyContent:'space-between',alignItems:'center',padding:18,textAlign:'left',fontWeight:600,color:'var(--caprice-fg)',fontSize:14}}>{q}<ChevronDown size={18} style={{transform:isOpen?'rotate(180deg)':'none',transition:'transform .2s',flex:'none',color:'var(--caprice-accent)'}}/></button>{isOpen&&<div style={{padding:'0 18px 18px',color:'var(--caprice-muted-fg)',lineHeight:1.6,fontSize:13}}>{a}</div>}</div>})}</div><div style={{background:'#211a15',color:'#fff',padding:24,borderRadius:24,margin:'24px 0'}}><h3 style={{fontFamily:'Georgia,serif',fontSize:20,marginBottom:8}}>Vous ne trouvez pas votre réponse ?</h3><p style={{color:'#cdbca5',fontSize:13,lineHeight:1.6,marginBottom:16}}>Contactez notre équipe directement, nous sommes là pour vous.</p><a href="tel:+241000000" style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8,background:'#f5ead8',color:'#221b15',padding:14,borderRadius:14,fontWeight:700}}>Appeler le restaurant</a></div></main>;}